### PR TITLE
Add Derive(Deserialize) to AST structs

### PR DESCRIPTION
**Pull request by Brandon-Rozek**
## Description of changes
Added Derive(Deserialize) to the AST structs used within `AuthorizationRequest`.

This allows us to test roundtrip equality which catches issues like #1042 

Note that this assumes that PR #1047 is merged first. 

## Issue #, if available
N/A

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):
- [x] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)

I confirm that this PR (choose one, and delete the other options):
- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):
- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.
- This PR by itself does not affect DRT, but #1047 which this is based on does.

### CODE REVIEW

**Review by john-h-kastner-aws — COMMENTED** [review]
Not sure I like this change. Needing to maintain a deserialize implementation makes it harder to change the internal representation used for these structs, and we don't need the deserialization impl for anything other than these tests

**Comment by emina** [comment]
Ah, it's interesting to see that we didn't have or need this deserialization code before.  

From a testing point of view, it would be nice to retain the code so we can catch bugs (if any) in the de/serialization on the Rust side.  Though I understand John's concerns about maintaining more code just for the purpose of testing.  

Curious to see what others think.

**Comment by john-h-kastner-aws** [comment]
I don't think the de-serialization make this _so_ much worse. Really, the fact that DRT depends on the serialization (and hence our internal representation) of these structures is the more annoying part.

**Comment by aaronjeline** [comment]
Closed

**Pull request closed without merging**
