### PR TITLE
cedar#745 for PolicyToJsonError

### PR DESCRIPTION
**Pull request by cdisselkoen**
## Description of changes

Applies the recommendations in #745 for `PolicyToJsonError`.

Questions:

- Do we like how this looks? Do we want to change the recommendations in any way?
- We'll end up with a large number of these member structs that are `pub` but with private fields.  Should we organize them into submodules?  One submodule per error enum or something?

## Issue #, if available

#745

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).

I confirm that this PR (choose one, and delete the other options):

No changelog update, let's do one at the end for all of #745.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

**Review by aaronjeline — APPROVED** [review]
The other option is returning `Box<dyn ..>` is there a reason against that?

**Comment by cdisselkoen** [comment]
That would correspond roughly to Pattern A in #745.  #745 covers some reasons for recommending what it calls Pattern C, which is implemented here.  If we don't like how this looks, we can consider Patterns A or B

**Comment by aaronjeline** [comment]
> That would correspond roughly to Pattern A in #745. #745 covers some reasons for recommending what it calls Pattern C, which is implemented here. If we don't like how this looks, we can consider Patterns A or B

Caching that discussion back into brain

**Review by john-h-kastner-aws — APPROVED** [review]
I like how this looks, but +1 to grouping errors into modules.
We'll end up with a lot of structs. The only thing to consider with that is that we might want to re-use error structs between different enums which could end up looking a bit odd when they're in different modules, but that's probably fine.

**Comment by cdisselkoen** [comment]
Moved the two new error structs into a submodule.  Not sure if we want a submodule per top-level error type, or just by general category, or just one submodule for detailed error structs.  Current PR does the second option.  Can always move errors between submodules prior to 4.0 release.

**Comment by cdisselkoen** [comment]
I'm unsure whether the Java CI failure is related to this PR or not

**Review by john-h-kastner-aws — APPROVED** [review]

**Comment by cdisselkoen** [comment]
The Java CI failure is unrelated and will be addressed separately.

**Pull request merged**
