### PR TITLE
Convert policy to json

### PR DESCRIPTION
**Pull request by memark**
## Description of changes

Adding a new command `translate-policy` that takes a human-readable policy set as input, and outputs a JSON string.

Since the linked issue suggests JSON -> human conversion is also desirable, and to keep parity with `translate-schema`, I've included a "translation direction" enum for this command as well, even though it currently only has one value.

## Issue #, if available
https://github.com/cedar-policy/cedar/issues/461

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

**Review by cdisselkoen — APPROVED** [review]
Looks great!  Maybe a test for this functionality?

**Comment by andrewmwells-amazon** [comment]
LGTM. +1 to adding a test case.

**Comment by memark** [comment]
I added a test, but other tests keep breaking. First the local format unit test, now the formatting integration test. Where and how should I place my test files not to affect other tests? Maybe I could just inline their content?

**Comment by john-h-kastner-aws** [comment]
If you install `cargo-insta` and then `cargo insta review` it will update the format tests. The you just need to commit the new snapshot file

**Review by john-h-kastner-aws — APPROVED** [review]

**Comment by john-h-kastner-aws** [comment]
Looks good. Remaining errors are downstream build failures unrelated to this PR.

**Pull request merged**
