### PR TITLE
Cherry-pick PRs to the 4.1.x release

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Description of changes

* #1199
* #1181 
* #1202 
* #1204 
* #1209 
* #1211 
* #1207
* #1215 
* #1213
* #1149 
* #1223 
* #1220 
* #1218 
* #1228 
* #1230 
* #1219

### CODE REVIEW

**Comment by khieta** [comment]
Is there a reason you can't directly use `main` as 4.1? I think that would make things easier to keep track of, moving forward.

**Comment by shaobo-he-aws** [comment]
> Is there a reason you can't directly use `main` as 4.1? I think that would make things easier to keep track of, moving forward.

I'm concerned if there's anything that shouldn't be released in main. Like Oliver's work.

**Comment by khieta** [comment]
> I'm concerned if there's anything that shouldn't be released in main. Like Oliver's work.

Wouldn't it be easier to just revert #1102 ?

**Comment by shaobo-he-aws** [comment]
> > I'm concerned if there's anything that shouldn't be released in main. Like Oliver's work.
> 
> Wouldn't it be easier to just revert #1102 ?

Good point.

**Pull request closed without merging**
