### PR TITLE
Cherry-pick PRs to `release/3.2.x`

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Description of changes

* #661 
* #685 
* #716 
* #713 
* #783
* #749 
* #771 
* #766 
* #802
* #808
* #809
* #811
* #818
* #836
* #825

### CODE REVIEW

**Review by andrewmwells-amazon — APPROVED** [review]

**Comment by andrewmwells-amazon** [comment]
Let's fix the lints on main and cherry-pick instead of clippy-fixing this PR
https://github.com/cedar-policy/cedar/pull/840

**Comment by john-h-kastner-aws** [comment]
I can cherry-pick #802, #808 and a few other recent error message improvements

**Comment by shaobo-he-aws** [comment]
Need to revert #783 because it's a breaking change.

**Comment by shaobo-he-aws** [comment]
SemVer checks now pass, at the expense of having four unreachable enum variants of `SchemaError` in `api.rs`.

**Comment by cdisselkoen** [comment]
Can we keep the PR description updated with the list of cherry-picked commits?

**Comment by cdisselkoen** [comment]
More PRs that we could possibly cherry-pick:

* #838 
* #835 
* #825 and #827 
* #798 ?
* #795 and #799 ?
* #788 
* #734

More generally there might be other PRs where in the checklist we marked "minor" or "patch" that could be cherry-picked.

**Comment by khieta** [comment]
I'd also like to see #707 and #725 (which deprecate the old integration testing code) cherry picked to v3.2.

**Comment by cdisselkoen** [comment]
My comments shouldn't be construed as blocking the merging of this PR; we can always cherry-pick additional commits in a followup PR.

**Comment by john-h-kastner-aws** [comment]
I found it easier to add new PRs when cherry-picking everything  in order they were originally committed.  Closing in favor of #845

**Pull request closed without merging**
