### PR TITLE
Use cedar-policy `README.md` as crate top-level documentation

### LINKED ISSUE #362: docs.rs documentation improvement
### Category

Documentation and code comments

### Describe the feature you'd like to request

On the Rust crate documentation (e.g., https://docs.rs/cedar-policy/latest/cedar_policy/) there are no usage examples on the landing pages, just snippet examples for the particular API calls. When you get to the landing page, you are looking for help, but instead you get a long list of types and API calls with no explanation.

I like the worked example we have on the [crates.io page for cedar-policy](https://crates.io/crates/cedar-policy); could we something like that for our various packages, too? I see this is done for other Rust packages, e.g., https://docs.rs/graph/latest/graph/ and https://docs.rs/bigdecimal/latest/bigdecimal/ as two random cases.

### Describe alternatives you've considered

Not really. Doing nothing = status quo.

### Additional context

_No response_

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

### PR DESCRIPTION
**Pull request by john-h-kastner-aws**
Edit: updated to make it top level docs.

---

It's a little bit hacky, but this is the simplest way I found to run the actual code that's in the readme. ([See the test execute here](https://github.com/cedar-policy/cedar/actions/runs/6655106480/job/18084606177?pr=386#step:7:1502))

A nicer option that avoids adding the dummy function could be running `rustdoc --test README.md` in CI, but `rustdoc` doesn't resolve the `cedar_policy::*` import, and `cargo doc --test` doesn't exist.

Another alternative could be using `#![doc = include_str!("../README.md")]` as the top level crate documentation. This would resolve the docs issue #362 and test the example at the same time, if were happy to use the exact same text in the README and crate docs.

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by khieta** [comment]
Thanks @john-h-kastner-aws! We should definitely be making sure that our README example compiles.

I like your `#![doc = include_str!("../README.md")]` alternative. What are the downsides of that?

**Comment by john-h-kastner-aws** [comment]
> What are the downsides of that?

Mainly that some part of the readme might not be useful to some one looking at the crates docs like the Documentation, Building, and Contributing sections. There could be further drift over time, but if we're happy using the current readme in both places, then we could address any other issues later.

**Comment by khieta** [comment]
I think we should just go for it. Even if the README has some info that is not relevant on crates.io, at least it will be maintained and the two sources will stay in sync.

**Comment by cdisselkoen** [comment]
Yeah it's definitely an improvement on the status quo for very little effort

**Comment by john-h-kastner-aws** [comment]
Looks nice!

image

**Review by khieta — APPROVED** [review]

**Pull request merged**
