### PR TITLE
Cherry-pick PRs for release 3.1.3

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Description of changes

* #653 
* #734 
* #708 
* #756 
* #751 
* #759 
* #758 
* #780 
* #698

### CODE REVIEW

**Comment by khieta** [comment]
Fyi #653 is marked as a breaking change in its PR.

**Comment by john-h-kastner-aws** [comment]
#698 is another candidate for the patch release

**Comment by shaobo-he-aws** [comment]
> #698 is another candidate for the patch release

It's marked as "A backwards-compatible change requiring a minor version bump to cedar-policy." But I didn't see why it should be. I will add it to this PR.

**Comment by shaobo-he-aws** [comment]
> #653 is marked as a breaking change in its PR. Is this accurate? @aaronjeline

I don't think it's a breaking change by inspecting the PR.

**Review by john-h-kastner-aws — APPROVED** [review]

**Pull request merged**
