### PR TITLE
Make format and check-parse CLI subcommands consistent

### PR DESCRIPTION
**Pull request by svanderbleek**
## Issue #403

Based on discussion of format and check-parse in linked issue, specifically:

> If we make format use -p and --policies instead of a positional argument, then I think we can call it good.

This should close that issue out by making the two subcommands consistent. It only requires a small renaming change for format in the code. I updated the changelog to note the removal of the positional argument for format.

## Checklist for requesting a review

The change in this PR is:

- [x] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).

I confirm that this PR:

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec):

- [x] Does not require updates because my change does not impact the Cedar Dafny model or DRT infrastructure.

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by andrewmwells-amazon — APPROVED** [review]

**Review by john-h-kastner-aws — APPROVED** [review]
Looks good. Thanks again!

**Comment by svanderbleek** [comment]
Cool, just had a to fix a failing test I missed for the positional change.

**Comment by svanderbleek** [comment]
I don't understand what the "Build Downstream Dependencies" is doing.

**Review by john-h-kastner-aws — APPROVED** [review]
Failing downstream is due to #393. Nothing to fix here.

**Pull request merged**
