### PR TITLE
bump version numbers on `main`

### PR DESCRIPTION
**Pull request by cdisselkoen**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by khieta** [comment]
Definitely time to update these version numbers 🙂 But I think I'd prefer bumping them to the next major version (4.0) to avoid any confusion with the 3.1.0 version on crates.io.

**Review by aaronjeline — APPROVED** [review]

**Comment by cdisselkoen** [comment]
@khieta what if we end up cutting the 3.2.x release branch from `main` like we did for 3.1.x?

I guess we'd just have to down-bump the version numbers on the 3.2.x release branch after reverting the PRs with breaking changes.  Is that the system we want?

**Comment by khieta** [comment]
> what if we end up cutting the 3.2.x release branch from main like we did for 3.1.x?
>
> I guess we'd just have to down-bump the version numbers on the 3.2.x release branch after reverting the PRs with breaking changes. Is that the system we want?

Personally, I think this is fine. We are already used to doing version number doctoring before we release, so this isn't a big change from the status quo. (Note that with your current PR we'd have to change 3.1 -> 3.2 before release.) I feel like it makes more sense for the `main` branch to be 4.0 than 3.2 because it currently contains breaking changes that will have to wait until the next major release.

**Comment by cdisselkoen** [comment]
Sure, you've sold me.

**Review by khieta — APPROVED** [review]

**Pull request merged**
