### PR TITLE
Refactor the handling of negative numbers in CST to EST conversion

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
Now it should be the same as CST to AST conversion

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A breaking change requiring a major version bump to `cedar-policy` (e.g., changes to the signature of an existing API).
- [ ] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).
- [ ] A bug fix or other functionality change requiring a patch to `cedar-policy`.
- [ ] A change "invisible" to users (e.g., documentation, changes to "internal" crates like `cedar-policy-core`, `cedar-validator`, etc.)
- [ ] A change (breaking or otherwise) that only impacts unreleased or experimental code.

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).
- [ ] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.
- [ ] Requires updates, and I have made / will make these updates myself. (Please include in your description a timeline or link to the relevant PR in `cedar-spec`, and how you have tested that your updates are correct.)
- [ ] Requires updates, but I do not plan to make them in the near future. (Make sure that your changes are hidden behind a feature flag to mark them as experimental.)
- [ ] I'm not sure how my change impacts `cedar-spec`. (Post your PR anyways, and we'll discuss in the comments.)

## Disclaimer

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by john-h-kastner-aws — COMMENTED** [review]
Is there a behavior change here, or just reorganizing the code?

**Comment by shaobo-he-aws** [comment]
> Is there a behavior change here, or just reorganizing the code?

It will lead to behavior change. For example, CST `-(1)` gets converted to EST literal `-1` before the change and it's EST negation expression `-(1)` after the change.

**Comment by cdisselkoen** [comment]
Do we want that behavior change?  Wouldn't it be better to produce the literal `-1` when possible, for users trying to programmatically consume/edit policies?

**Comment by shaobo-he-aws** [comment]
> Do we want that behavior change? Wouldn't it be better to produce the literal `-1` when possible, for users trying to programmatically consume/edit policies?

The roundtrip PBT fails without the fix. I think we should strive for consistency for CST to EST and CST to AST conversion.

**Review by aaronjeline — APPROVED** [review]

**Review by andrewmwells-amazon — APPROVED** [review]

**Comment by andrewmwells-amazon** [comment]
> Do we want that behavior change? Wouldn't it be better to produce the literal -1 when possible, for users trying to programmatically consume/edit policies?

I think it's ok. I don't see why people would write -(1), so I doubt it affects anyone. And it's a fairly intuitive that we handle the parenthesized part before negation, so I don't think people will have trouble understanding the behavior.

**Pull request merged**
