### PR TITLE
Add error codes to Cedar errors

### PR DESCRIPTION
**Pull request by shaobo-he-aws**
## Issue #, if available

#184 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A backwards-compatible change requiring a minor version bump to `cedar-policy` (e.g., addition of a new API).

I confirm that this PR (choose one, and delete the other options):

- [x] Updates the "Unreleased" section of the CHANGELOG with a description of my change (required for major/minor version bumps).

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

**Comment by cdisselkoen** [comment]
+1, we want to use miette's `code`.

**Comment by shaobo-he-aws** [comment]
I tried to use `code` but concluded it's not a good idea. We need annotations like `[diagnostic(code("A100"))]`, IIUC. Then, annotating each case is error prone (e.g., duplicate error code). And it's hard to update the error code. That's why I made a trait and use its `error_code` method in `Diagnostic::code`.

I think using the `code` annotation makes sense if we want namespaced and more descriptive error code like `cedar::evaluation::type_error`. I can implement this option if we think it's better.

**Comment by shaobo-he-aws** [comment]
The current implementation [da8b18d](https://github.com/cedar-policy/cedar/pull/743/commits/da8b18d523c6780ae97ce645a432049b1b4876b7) follows these rules:

1. Evaluation error codes start with "evaluation" and evaluation error codes start with "validation".
2. If the error kind arm is an enum, add a new namespace component (e.g., integer overflow error codes start with "evaluation::integer_overflow").
3. Namespace components except for the first one are (mostly) the snake-case counterparts of enum arm identifiers.

**Comment by aaronjeline** [comment]
Superseded

**Pull request closed without merging**
