### PR TITLE
update integration tests for #814

### PR DESCRIPTION
**Pull request by cdisselkoen**
## Description of changes

Update integration tests for the changes in #814.  This was missed in #814 itself, perhaps we should check our CI?

## Issue #, if available

#814 

## Checklist for requesting a review

The change in this PR is (choose one, and delete the other options):

- [x] A bug fix or other functionality change requiring a patch to `cedar-policy`.

I confirm that this PR (choose one, and delete the other options):

- [x] Does not update the CHANGELOG because my change does not significantly impact released code.

I confirm that [`cedar-spec`](https://github.com/cedar-policy/cedar-spec) (choose one, and delete the other options):

- [x] Does not require updates because my change does not impact the Cedar formal model or DRT infrastructure.

### CODE REVIEW

**Comment by khieta** [comment]
The CI is currently using https://github.com/cedar-policy/cedar-integration-tests (only Java is still using the old folder in this repo). I would have expected CI to fail though -- do integration tests run successfully locally? You can run them locally following the instruction in the README here https://github.com/cedar-policy/cedar/tree/main/cedar-testing

**Comment by cdisselkoen** [comment]
Well, in #814 the Java CI failed, which was expected (the Java updates for #814 are in cedar-policy/cedar-java#129).  Your comment explains why _only_ the Java CI failed, and not the CI in this repo.  We should at some point fix the Java to use https://github.com/cedar-policy/cedar-integration-tests like everything else, and then delete this folder, then?

**Review by shaobo-he-aws — APPROVED** [review]

**Comment by khieta** [comment]
Yes, the plan is to delete the folder here -- I should make an issue to track. The current blocker is that the new integration test repo uses the new schema format, which the Java doesn't support. I figured we'd add support for this in the Java as part of the updates for #757.

**Review by john-h-kastner-aws — APPROVED** [review]

**Comment by cdisselkoen** [comment]
Java CI is failing on this PR due to https://github.com/cedar-policy/cedar-java/pull/129 not being merged yet.  This is expected.  I will merge this, even though there is not really any specific test that this PR solved the issue it's trying to address.  Worst case, we need another followup PR.

**Pull request merged**
